name: Free VPS Ubuntu + V2Ray

on:
  workflow_dispatch:

jobs:
  setup-vps:
    runs-on: ubuntu-latest
    steps:
      # سحب ملفات المستودع
      - name: Checkout repository
        uses: actions/checkout@v3

      # تحديث النظام وتثبيت الأدوات الضرورية
      - name: Update & install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl git unzip

      # تثبيت V2Ray بصلاحيات root
      - name: Install V2Ray
        run: |
          sudo bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)

      # تحديث DuckDNS بالدومين الخاص بك
      - name: Update DuckDNS
        run: |
          curl -k "https://www.duckdns.org/update?domains=myvps01v2ry&ip="

      # عرض معلومات VPS
      - name: Show VPS info
        run: |
          echo "VPS Setup Done"
          hostname -I
