name: Free VPS Docker + V2Ray

on:
  workflow_dispatch:

jobs:
  setup-vps:
    runs-on: ubuntu-latest
    steps:
      # سحب ملفات المستودع
      - name: Checkout repository
        uses: actions/checkout@v3

      # التحقق من وجود Docker
      - name: Check Docker version
        run: |
          docker --version

      # تشغيل V2Ray في Docker Container باستخدام صورة محدثة
      - name: Run V2Ray container
        run: |
          docker run -d --name v2ray \
          -p 1080:1080 \
          -p 443:443 \
          teddysun/v2ray

      # تحديث DuckDNS بالدومين الخاص بك
      - name: Update DuckDNS
        run: |
          curl -k "https://www.duckdns.org/update?domains=myvps01v2ry&ip="

      # عرض حالة الحاوية والمعلومات
      - name: Show VPS info
        run: |
          echo "V2Ray Docker container is running"
          docker ps
          hostname -I
