name: Free VPS Docker + V2Ray

on:
  workflow_dispatch:

jobs:
  setup-vps:
    runs-on: ubuntu-latest
    steps:
      # سحب ملفات المستودع
      - name: Checkout repository
        uses: actions/checkout@v3

      # تحديث النظام وتثبيت Docker
      - name: Update & install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # تشغيل V2Ray في Docker Container
      - name: Run V2Ray container
        run: |
          sudo docker run -d --name v2ray \
          -p 1080:1080 \
          -p 443:443 \
          v2fly/v2ray-core

      # تحديث DuckDNS بالدومين الخاص بك
      - name: Update DuckDNS
        run: |
          curl -k "https://www.duckdns.org/update?domains=myvps01v2ry&ip="

      # عرض حالة الحاوية والمعلومات
      - name: Show VPS info
        run: |
          echo "V2Ray Docker container is running"
          sudo docker ps
          hostname -I
